version: "3"
services:
  app:
    container_name: hooligan-hymnal-server
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hymnal
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo